### ISSUE TITLE
unable to run drush from script

### ISSUE THREAD

**Issue by jimrome** [WebKings-ca/gocomposer#10] opened 2020-02-06 16:03 UTC
> wwwrun@jardell:/srv/www/htdocs/orcma> /srv/www/htdocs/orcma/public_html/vendor/bin/drush
PHP Warning:  require(/srv/www/htdocs/orcma/public_html/vendor/bin/drush.php): failed to open stream: No such file or directory in /srv/www/htdocs/orcma/public_html/vendor/bin/drush on line 4
PHP Fatal error:  require(): Failed opening required '/srv/www/htdocs/orcma/public_html/vendor/bin/drush.php' (include_path='.:/usr/share/php7:/usr/share/php7/PEAR') in /srv/www/htdocs/orcma/public_html/vendor/bin/drush on line 4
wwwrun@jardell:/srv/www/htdocs/orcma> ls -l /srv/www/htdocs/orcma/public_html/vendor/bin/drush
-rwxr-xr-x 1 wwwrun www 58 Feb  6 10:16 /srv/www/htdocs/orcma/public_html/vendor/bin/drush
wwwrun@jardell:/srv/www/htdocs/orcma>

So things fail.
 But before the script runs,

> > ls -l vendor/bin
> total 44
> -rwxr-xr-x 1 wwwrun www 1181 Feb  6 10:59 dcg
**> -rwxr-xr-x 1 wwwrun www   58 Feb  6 10:59 drush**
 and after it runs:

> /vendor/bin> ls -l
> total 72
> lrwxrwxrwx 1 wwwrun www   33 Feb  6 10:46 composer -> ../composer/composer/bin/composer
> -rwxr-xr-x 1 wwwrun www 1181 Feb  6 10:16 dcg
> lrwxrwxrwx 1 wwwrun www   28 Feb  6 10:46 drupal -> ../drupal/console/bin/drupal
**> -rwxr-xr-x 1 wwwrun www    0 Feb  6 10:55 drush**
So drush is getting munged. It is still in vendor/drush/drush

Also, running this updated me to drupal 8.9

**Comment by jimrome** [comment] 2020-02-06 16:07
> wwwrun@jardell:/srv/www/htdocs/orcma/public_html> ls -l drush
> lrwxrwxrwx 1 wwwrun www 24 Feb  6 10:59 drush -> vendor/drush/drush/drushwwwrun@jardell:/srv/www/htdocs/orcma/public_html> ls -l drush
> lrwxrwxrwx 1 wwwrun www 24 Feb  6 10:59 drush -> vendor/drush/drush/drush

and ./drush works

**Comment by jimrome** [comment] 2020-02-06 16:10
ignore the time stamps in the above. I cut and pasted at different times.

**Comment by jimrome** [comment] 2020-02-06 16:22
This is all asroot:
/public_html # vendor/bin/drush

> PHP Warning:  require(/srv/www/htdocs/orcma/public_html/vendor/bin/drush.php): failed to open stream: No such file or directory in /srv/www/htdocs/orcma/public_html/vendor/bin/drush on line 4
> PHP Fatal error:  require(): Failed opening required '/srv/www/htdocs/orcma/public_html/vendor/bin/drush.php' (include_path='.:/usr/share/php7:/usr/share/php7/PEAR') in /srv/www/htdocs/orcma/public_html/vendor/bin/drush on line 4
> jardell:/srv/www/htdocs/orcma/public_html # ls /srv/www/htdocs/orcma/public_html/vendor/bin/drush
> /srv/www/htdocs/orcma/public_html/vendor/bin/drush
Running 
vendor/drush/drush/drush
 works and
/srv/www/htdocs/orcma/public_html/vendor/drush/drush/drush
works, but 
/srv/www/htdocs/orcma/public_html/vendor/bin/drush
does not. 

> # ls -l vendor/bin/drush
> -rwxr-xr-x 1 wwwrun www 58 Feb  6 10:59 vendor/bin/drush

works

**Comment by jimrome** [comment] 2020-02-06 16:36
FIXED DRUSH
Your script works if I copy vendor/drush/drush drush.php to vendor/bin. It would be better yo use the vendor/drush/drush directory instead of vendor/bin

BUT then after successfully backing up all the files and the db, I get:

> Current Step: Getting Latest template for drupal-composer/drupal-project
> ------------------------------------------------------------------------
> 
> /srv/www/htdocs/orcma/public_html/vendor/webkings-ca/gocomposer/script.sh: line 23: ./composer: No such file or directory
> /srv/www/htdocs/orcma/public_html/vendor/webkings-ca/gocomposer/script.sh: line 25: cd: d8LatestTemplate: No such file or directory

and then, it fails at

> Current Step: Modifying your file structure to the Latest template from drupal-composer/drupal-project
> ------------------------------------------------------------------------------------------------------
> cp: cannot create directory '/srv/www/htdocs/orcma/public_html/web/sites/': No such file or directory
There is no web directory!!

**Comment by jimrome** [comment] 2020-02-06 17:56
It got a lot further if I created a web directory, and copied drush.php to vendor/bin. But it still fails to get the new template (I added a few echos to your script):

> Current Step: Getting Latest template for drupal-composer/drupal-project
> ------------------------------------------------------------------------
> /srv/www/htdocs/orcma/public_html/vendor/webkings-ca/gocomposer/script.sh: line 23: ./composer: No such file or directory
> /srv/www/htdocs/orcma/public_html/vendor/webkings-ca/gocomposer/script.sh: line 25: cd: d8LatestTemplate: No such file or directory
> in script.sh: mainDir=/srv/www/htdocs/orcma/public_html, composerPhar=./composer
And at the end, there are no php files in the web directory, so nothing to run.

> public_html/web # ls -a
> .  ..  core  modules  sites  themes

**Comment by WebKings-ca** [comment] 2020-02-06 18:06
@jimrome , Glad that you have fixed the drush issue... It seems from the error log you have last posted that it might be either a permission issue or that in your environment set up your `composer.phar` executable is located in a different path than the normal... This is probably due to the environment and server setup configuration you have.. If thats the case, see this line: (Line 470, GoComposerCommand.php)

`$composerPhar = $_SERVER['SCRIPT_FILENAME'];`

Try to change it to the path that your `composer.phar` is located in.. Please do test both solutions and post the outcome here... Also, are you in a Local environment or production?

Thanks...

**Comment by jimrome** [comment] 2020-02-06 18:36
Local environment. composer.phar is in my public_html (site root) directory where the drupal files are placed.
Where is GoComposerCommand.php?

> htdocs/orcma # find ./ -type f -exec grep -H 'GoComposerCommand.php' {} \;
> Binary file ./public_html-2-4-2020-dell.zip matches
> Binary file ./public_html.good/gocomposer-master.zip matches
> Binary file ./public_html.good/vendor/webkings-ca/gocomposer/.git/index matches
> Binary file ./public_html/gocomposer-master.zip matches
> Binary file ./public_html/vendor/webkings-ca/gocomposer/.git/index matches

**Comment by jimrome** [comment] 2020-02-06 19:36
I found the file. How do I fix that line to use "/srv/www/htdocs/orcma/public_html/composer.phar"

**Comment by jimrome** [comment] 2020-02-06 19:47
$composerPhar = "/srv/www/htdocs/orcma/public_html/composer.phar";
worked.
I am also confused about how to answer the prompt:

> Updating dependencies (including require-dev)
> Package operations: 137 installs, 46 updates, 5 removals
>   - Removing wikimedia/composer-merge-plugin (v1.4.1)
>   - Removing webkings-ca/gocomposer (dev-master)
>     The package has modified files:
>     D composer.json
>     D composer.lock
>     M src/Composer/GoComposerCommand.php
>     M template.composer.json
>     Discard changes [y,n,v,d,?]?
I don't want to discard the changes.
I answered yes.
But then I get a bunch of warnings like:
[warning] The following module is missing from the file system: genpass bootstrap.inc:295
and missing libraries:

> [error]  Panelbutton requires the plugin.js library.
>        Download the plugin from http://ckeditor.com/addon/panelbutton at least
>        version 4.5.6, and place it in the libraries folder
>        (/libraries/panelbutton) (Currently using Panelbutton library is missing Plugin not detected)

**Comment by jimrome** [comment] 2020-02-06 19:50
And all my libraries (and the directory) are gone.

**Comment by jimrome** [comment] 2020-02-06 19:51
And libraries is not listed in your folder structure. Where does it go?

**Comment by jimrome** [comment] 2020-02-06 20:26
I copied my old libraries to web/libraries. But, even after reinstalling the simpleaddress module, I get errors:

> jardell:/srv/www/htdocs/orcma/public_html # ./drush cr
> 
> In FieldStorageConfigStorage.php line 174:
> 
>   Unable to determine class for field type 'simpleaddress' found in the 'field.storage.node.field_edmailing_address' configuration
> 
> 
> In DiscoveryTrait.php line 53:
> 
>   The "simpleaddress" plugin does not exist. Valid plugin IDs for Drupal\Core\Field\FieldTypePluginManager are: comment, datetime, entity_reference_revisions, feeds_item, file, file_uri
>   , geolocation, image, link, mailchimp_lists_subscription, metatag, list_float, list_integer, list_string, path, plugin:payment_line_item, plugin:payment_method, plugin:payment_status,
>    plugin:payment_type, payment_form, plugin:currency_amount_formatter, plugin:currency_exchange_rate_provider, plugin:payment_method_configuration, plugin:plugin_selector, plugin:entit
>   y_reference_selector, plugin:field_widget, plugin:field_formatter, plugin:archiver, plugin:action, plugin:menu_link, plugin:menu_local_action, plugin:menu_local_task, plugin:menu_lcon
>   textual_link, plugin:display_variant, plugin:queue_worker, plugin:mail, plugin:condition, plugin:element, plugin:block, plugin:ckeditor_plugin, plugin:editor, plugin:filter, plugin:im
>   age_effect, plugin:quickedit_editor, plugin:search, plugin:tour_tip, plugin:views_access, plugin:views_area, plugin:views_argument, plugin:views_argument_default, plugin:views_argumen
>   t_validator, plugin:views_cache, plugin:views_display_extender, plugin:views_display, plugin:views_exposed_form, plugin:views_field, plugin:views_filter, plugin:views_join, plugin:vie
>   ws_pager, plugin:views_query, plugin:views_relationship, plugin:views_row, plugin:views_sort, plugin:views_style, plugin:views_wizard, telephone, text, text_long, text_with_summary, v
>   ideo_embed_field, webform, boolean, changed, created, decimal, email, entity_reference, float, integer, language, map, password, string, string_long, timestamp, uri, uuid

I also think you install things with --dev. Most do not want that. Ask the user?

After generating the lock file:

> Writing lock file
> Generating autoload files
> > DrupalProject\composer\ScriptHandler::createRequiredFiles
> cp: failed to access '/srv/www/htdocs/orcma/public_html/drush/': Not a directory
> cp: cannot stat '/srv/www/htdocs/orcma/public_html/Libraries/.': No such file or directory
> cp: cannot stat '/srv/www/htdocs/orcma/public_html/modules/custom/.': No such file or directory

You had deleted my old libraries directory.

**Comment by WebKings-ca** [comment] 2020-02-06 21:29
@jimrome ,

It seems the issue has to do with your current Local Environment setup and other permission issues. Please inform me of the following:

1) Which PHP version are you using?
2) Which MySql Version are you using?
3) What is the stack you're using on your computer?
4) Since this is your local computer, is it Linux, Unix or PC based?
5) Composer is it installed globally on your computer?
6) Did you check the permissions you're running as a user or super user?
7) What is the original Drupal Core version you're running the command on?

As for the Libraries not listed in the diagram that's due to an omission in the diagram... The plugin works perfectly and copies over the `/Libraries` folder to `/web/libraries`... I will fix the diagram when I have time...

Also, Please post the full output (in code tags) from start of running command all the way till it terminates processing (Exact full output please). 

After posting this information I can then easily tell you if it is an error in your setup or due to the plugin... thanks...

**Comment by jimrome** [comment] 2020-02-06 21:41
Which PHP version are you using?  _PHP 7.2.5 (cli) ( NTS )_
    Which MySql Version are you using?  _Mariadb 10.2.29-lp151.2.9.1_ 
    What is the stack you're using on your computer?  _apache2, tomcat_
    Since this is your local computer, is it Linux, Unix or PC based? _OpenSUSE Leap 15.1_
    Composer is it installed globally on your computer? I have multiple Drupal sites under /srv/www/htdocs, so I have a composer.phar (linked to composer) in each site main directory.
    Did you check the permissions you're running as a user or super user? I did
chown -R wwwrun:www htdocs
I run composer and your gocomposer in a root shell, so there should be no permission issues. I also tried it as wwwrun.
    What is the original Drupal Core version you're running the command on?  8.8.2
BTW, the line endings in the  shell scripts have the wrong line endings for linux.

**Comment by WebKings-ca** [comment] 2020-02-06 22:01
The problem is in your server setup as it seems the current config your giving is all over the place... Using Tomcat with apache is very, very rare as it used mostly for Java., Check out the following link:

https://www.drupal.org/forum/general/general-discussion/2007-04-23/will-drupal-work-on-apache-tomcat

Also, you didn't provide the following:
 - Whether it is a mac or PC
- Composer is it installed Globally
- Whether your a Superuser or not
- Many of the details you have provided seem incorrect or missing
- You did not post the full output of the plug-in as requested.

It seems you're not that familiar to properly configure your server/environment and it is something that is outside the scope of this plug-in. Since I had requested the correct information multiple times and you were unable to provide it, I would advise you to learn more on how to properly configure your "Local Environment".. Closing this issue for now and Good Luck!

**Comment by jimrome** [comment] 2020-02-06 23:23
I did answer them all. I don't use tomcat for drupal, but I menmtioned it as part of my stack. Drupal just runs using apache2 and mariadb. Linux Opensuse LEAP 15.1.
The usual install does not put drush.php in vendor/bin: 

> /vendor/bin # ls
> dcg  drush  fileeye-mimemap  php-parse  psysh  release  robo  var-dump-server

Before running gocomposer, I

1. created web directory
2. Copied drush.php to vendor/bin
3. edited GoComposerCommand.php to put ibn the absolute path to composer.
[gocomposer.log](https://github.com/WebKings-ca/gocomposer/files/4168220/gocomposer.log)
See attached log

**Comment by jimrome** [comment] 2020-02-09 16:24
well? What is wrong in my install?

**Comment by WebKings-ca** [comment] 2020-02-09 17:18
@jimrome , You're not supposed to manually create the `/web` directory... The plugin automates this process and does it for you. Also, are you using a windows PC or an Apple Mac computer? Knowing this might help me in finding out what the issue is... In any case, Try the following:

1) Restore the Database and files to the exact state they were before applying GoComposer (You could use the files in the `/backup` folder to do this)

2) Make sure you're running Composer globally.

3) Make sure Not to create the `/web` directory. so your Drupal root is in `/srv/www/htdocs/orcma/public_html` in your case.

4) Run the GoComposer command from your Drupal root (`/srv/www/htdocs/orcma/public_html` in your case)

5) Post success of plugin or if there is an error please post log again here.

Thanks...

**Comment by jimrome** [comment] 2020-02-13 17:53
For the third time, I am running on Linux OpenSUSE Leap 15.1 and started with Drupal 8.8.2

Sorry. It took some time to avoid running out of memory for composer and drush.
1. I still had to copy vendor/bin/drush to vendor/bin/drush.php
2. At the end, no libraries directory was created
You ask for

> cp: cannot stat '/srv/www/htdocs/orcma/public_html/Libraries/.': No such file or directory

but in Linux, I have _libraries_, not _Libraries_.
# ls web
> .csslintrc     .eslintrc.json  .ht.router.php  INSTALL.txt  autoload.php  example.gitignore  modules   robots.txt  themes      web.config
> .eslintignore  .gitignore      .htaccess       README.txt   core          index.php          profiles  sites       update.php
> jardell:/srv/www/htdocs/orcma/public_html # ls
> .5              .htacces.4-18-2019        3000677-68.patch  ORSO.jpg             composer.lock                home.htaccess         update.php.5-2-19
> .csslintrc      .htaccess.bak.1506016456  3078671-36.patch  README.txt           composer.phar                index.html.sav        vendor
> .editorconfig   .htaccess.bak.1506016476  400.shtml         README.zip           drupal8_update.sh            index.php-5-2-19      web
> .env            .htaccess.bak.1515199314  401.shtml         adaptive-images.php  drush                        justhost.htaccess     wrong_composer_json-3023038-5.patch
> .eslintignore   .htaccess.bak.1529100367  403.shtml         autoload.php-5-2-19  entupfix.php-5-2-19          load.environment.php
> .eslintrc       .htaccess.bak.1529100460  404.shtml         backup               favicon.ico                  newsite
> .eslintrc.json  .htaccess3-13-18          500.php           cgi-bin              gocomposer-master            phpinfo.php
> .gitattributes  .travis.yml               500.shtml         composer             gocomposer-master.zip        scripts
> .gitignore      .well-known               LICENSE.txt       composer.json        google33370e2e29e47591.html  settings_orig.php
[gocomposer.log](https://github.com/WebKings-ca/gocomposer/files/4200068/gocomposer.log)
[gocomposer.log.zip](https://github.com/WebKings-ca/gocomposer/files/4200077/gocomposer.log.zip)


I still get errors:

> Current Step: Using Drush to update the Database... Press Enter to Continue...
> ------------------------------------------------------------------------------
> 
>  [warning] The following module is missing from the file system: advanced_text_formatter bootstrap.inc:295
>  [warning] The following module is missing from the file system: block_visibility_groups bootstrap.inc:295
>  [warning] The following module is missing from the file system: block_visibility_groups_admin bootstrap.inc:295
>  [warning] The following module is missing from the file system: controlled_fields bootstrap.inc:295
>  [warning] The following module is missing from the file system: ctools bootstrap.inc:295
>  [warning] The following module is missing from the file system: ctools_block bootstrap.inc:295
>  [warning] The following module is missing from the file system: ctools_views bootstrap.inc:295
>  [warning] The following module is missing from the file system: editor_file bootstrap.inc:295
>  [warning] The following module is missing from the file system: fblikebutton bootstrap.inc:295
>  [warning] The following module is missing from the file system: filter_form_values bootstrap.inc:295
>  [warning] The following module is missing from the file system: genpass bootstrap.inc:295
>  [warning] The following module is missing from the file system: google_analytics bootstrap.inc:295
>  [warning] The following module is missing from the file system: gtranslate bootstrap.inc:295
>  [warning] The following module is missing from the file system: imce bootstrap.inc:295
>  [warning] The following module is missing from the file system: insert bootstrap.inc:295
>  [warning] The following module is missing from the file system: juicebox bootstrap.inc:295
>  [warning] The following module is missing from the file system: libraries bootstrap.inc:295
>  [warning] The following module is missing from the file system: module_filter bootstrap.inc:295
>  [warning] The following module is missing from the file system: panels bootstrap.inc:295
>  [warning] The following module is missing from the file system: panels_ipe bootstrap.inc:295
>  [warning] The following module is missing from the file system: php bootstrap.inc:295
>  [warning] The following module is missing from the file system: publishcontent bootstrap.inc:295
>  [warning] The following module is missing from the file system: recaptcha bootstrap.inc:295
>  [warning] The following module is missing from the file system: rules_webform bootstrap.inc:295
>  [warning] The following module is missing from the file system: simpleaddress bootstrap.inc:295
>  [warning] The following module is missing from the file system: simple_image_rotate bootstrap.inc:295
>  [warning] The following module is missing from the file system: sitemap bootstrap.inc:295
>  [warning] The following module is missing from the file system: social_media_links bootstrap.inc:295
>  [warning] The following module is missing from the file system: statistics_counter bootstrap.inc:295
>  [warning] The following module is missing from the file system: superfish bootstrap.inc:295
>  [warning] The following module is missing from the file system: title bootstrap.inc:295
>  [warning] The following module is missing from the file system: video bootstrap.inc:295
>  [warning] The following module is missing from the file system: videojs bootstrap.inc:295
>  [warning] The following module is missing from the file system: views_field_view bootstrap.inc:295
>  [warning] The following module is missing from the file system: views_templates bootstrap.inc:295
>  [warning] The following module is missing from the file system: view_unpublished bootstrap.inc:295
>  [error]  Panelbutton requires the plugin.js library.
>        Download the plugin from http://ckeditor.com/addon/panelbutton at least
>        version 4.5.6, and place it in the libraries folder
>        (/libraries/panelbutton) (Currently using Panelbutton library is missing Plugin not detected)

I attach the log file.

**Comment by jimrome** [comment] 2020-02-13 18:08
After fixing the private directory path, I still get the same fatal error as before:

>   369298   13/Feb 18:05   php        Error      Drupal\Component\Plugin\Exception\PluginNotFoundException: Unable to determine class for field type 'simpleaddress'
>                                                 found in the 'field.field.user.user.field_mailing_address' configuration

**Comment by jimrome** [comment] 2020-02-13 18:13
I installed the simpleaddress module, but that did not fix things

**Comment by WebKings-ca** [comment] 2020-02-13 19:08
@jimrome, And for the third time you refuse to answer the simple question is it a Mac or Windows PC... My guess from your Drupal Root path: `/srv/www/htdocs/orcma/public_html` it's neither... It's in a production server environment. Hence, you're getting all the errors you're getting. As indicated in the ReadMe file of this plug-in it should be run in a local environment.

Anyway, for your case, I can offer you some advice on how to make it work in production but cannot go any further since the plug-in is designed for a local environment:

1) It seems that since in Linux everything is Case sensitive, that's why it's not copying over the "Libraries" folder. You have it as `/libraries` and the Plug-in is searching for `/Libraries` .  Rename your "libraries" folder to "Libraries". That should fix this issue and the issue you see when `drush updb` runs and indicates missing modules.

2) It seems your "drush" executable is in `./vendor/drush/drush/drush` copying it to `./vendor/bin/drush` will fix this issue.

3) Check you have the right permissions and Re-run the plug-in from the original version with all other unneeded files removed.

If that fixes it, please do provide me with an update in this thread. Otherwise, Please provide the answer for these side notes, 

Was your original Drupal site "composer based" ? and if so which composer.json template are you using? 

Were you using this one:
https://github.com/drupal-composer/drupal-project

Currently the recommended version has been changed. You can see it in the following link:
https://github.com/drupal/recommended-project/blob/8.8.x/composer.json

In the future, GoComposer will be updated to use the above template but that will come some time later.

If your original site is composer based please also post the contents of your composer.json file with the new error log.

**Comment by jimrome** [comment] 2020-02-13 20:01
It is a Dell Xenon server. If it is running Linux, it is not a Mac or a PC. It IS a local server--mine.
My site was converted to use composer. Don't remember the original template.
- 
[composer.json.zip](https://github.com/WebKings-ca/gocomposer/files/4200566/composer.json.zip)

The instructions for libraries in Drupal say to use "libraries". In Linux, it MUST be in lower case. But your script should accept either. Note the error message:

> error]  Panelbutton requires the plugin.js library.
>        Download the plugin from http://ckeditor.com/addon/panelbutton at least
>        version 4.5.6, and place it in the **libraries** folder
>        (**/libraries**/panelbutton) (Currently using Panelbutton library is missing Plugin not detected)

If I can fix the simpleaddress issue, I think the site will work. Otherwise I get the "website encountered an unexpected error. Please try again later." message.

**Comment by WebKings-ca** [comment] 2020-02-14 00:42
As I expected, You're running the **GoComposer** on your production server hence the many errors you are getting. As I informed you before multiple times: **_The Plugin is configured to be used on you're local Environment, Which means a local computer either Mac or Windows._** You want the plug-in to work? simple setup your _local computer_ with the proper _local environment_, run the plug-in there and then just move the files and database to your production server.

Please don't post any more comments if you don't follow the recommended way to use this plug-in. Should you try the **GoComposer** plug-in in a properly setup _local environment_ and still facing issues create a new issue with the required logs for that issue. **_Closing this thread permanently._**

**Closed as completed by WebKings-ca** 2020-02-14 00:42 UTC
